### ISSUE TITLE
C API to query overall Bedrock json configuration

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-bedrock#10]
It would be helpful for tools like mochi-quintain if there were a C API that could be used to emit the complete json configuration for a running daemon.  It would be fine for it to be a local function or a remote RPC.

I had been approximating this by report the cfg json for the mochi-quintain provider and margo, but I realized just now that this isn't enough to tell  you if a provider was explicitly mapped to a pool or not, since neither of those two components have visibility into that part.

**Comment by mdorier** [comment]
You want to emit the configuration from inside the provider? Or from a quintain client?

**Comment by carns** [comment]
Either one would be fine.  I ultimately want the json as a string on the rank 0 client so that it can be written into the benchmark output file as a record of the configuration.  Quintain already implements its own rpc that collects and concatenates local json configurations in string format and sends them to the  client, though, so it's not a big deal either way.

https://github.com/mochi-hpc/mochi-quintain/blob/main/src/quintain-server.c#L176

If the json could be retrieved with an RPC then I'll use it directly on the client side.  If it can be retrieved locally then I'll stick it in the above rpc handler and have the client invoke that.  I guess the former is a little more general for other use cases but I'm not picky.

**Comment by carns** [comment]
Yep!

**Comment by mdorier** [comment]
Can you test with the commit I just pushed? (just installing mochi-bedrock@main will do)
You need to pass a JX9 script to the `bedrock_service_query_config` function. If you want the full configuration, this should work:

```
return $__config__;
```

**Comment by carns** [comment]
Awesome!  That's very close.  A  few minor suggestions and questions:

- common.h should probably be included in client.h to pick up the BEDROCK_SUCCESS definition
- is there a variation on that jsx9 script that will pretty format the resulting json, by any chance?  The output I'm getting looks technically correct but its hard to read because there aren't any line breaks or indentation.

**Comment by mdorier** [comment]
Good point about the common.h, I added it.

For the JSON format, unfortunately not: the bedrock-query utility makes it pretty by re-parsing it with nlohman::json.
