### ISSUE TITLE
abt-io instances not finalized

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-bedrock#11]
I can make a clean reproducer and asan stack trace later today, but I wanted to go ahead and record the issue.  It looks like when Bedrock explicitly instantiates abt-io instances (i.e., with a `"abt_io" : [ ]` block in the json) the instances are not shut down when bedrock exits.  For me this mainly shows up as a verbose memory leak from asan (probably not particularly harmful, but the output obfuscates looking for other more relevant problems).

**Comment by mdorier** [comment]
Thanks! Can you try again with the commit I just pushed?

**Comment by carns** [comment]
Perfect!  Thanks @mdorier .  That eliminated all of the asan faults for the test case that I was trying.
