### ISSUE TITLE
mochi-bedrock not found

### ISSUE THREAD

**Issue by nono-Sang** [mochi-hpc/mochi-bedrock#12]
I can't install mochi-bedrock using spack, the error is as following:
`spack install mochi-bedrock`
`==> Error: Package 'mochi-bedrock' not found.`

Note: The spack version is 0.19.0.dev0

**Comment by roblatham00** [comment]
Bedrock is not part of spack core.  You'll need to add the "mochi" spack repository:  https://mochi.readthedocs.io/en/latest/installing.html#installing-spack-and-the-mochi-repository

If you did that, can you share the output of `spack repo list`?
