### ISSUE TITLE
unable to leave ssg group

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-bedrock#5]
This is a low priority bug, not blocking anything for me right now, but when I run bedrock with ssg enabled and swim disabled, then I see these error messages on shutdown:

```
[2022-01-21 13:23:19.086] [error] Could not leave SSG group "quintain" (ssg_group_leave returned 15)
Error: SSG unable to leave group if SWIM is disabled
```
My ssg configuration for bedrock looks like this:
```
    "ssg": {
        "name" : "quintain",
        "bootstrap" : "init",
        "group_file" : "quintain.ssg",
        "swim": {
                    "disabled": true
                }
    },
```
Possibly just an API thing that you aren't allowed to explicitly leave a group when swim isn't used, as the message indicates.  A bigger question might be if bedrock is supposed to explicitly leave the group at all, or just destroy the group on the way down?  Possibly a question for @shanedsnyder but I can help dig into it later too.

**Comment by mdorier** [comment]
Fixed on Bedrock's end. You'll still see the error printed by SSG though (@shanedsnyder I would suggest having SSG use the margo logging functions so that the messages get redirected to Bedrock. This particular error could also just be a warning.)
